/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.10.0.111.2 */
/* Module Version: 3.6 */
/* Thu Nov 14 15:54:50 2019 */

/* parameterized module instance */
comp __ (.DataA( ), .DataB( ), .AEQB( ));
