/* Verilog netlist generated by SCUBA Diamond (64-bit) 3.10.0.111.2 */
/* Module Version: 3.6 */
/* C:\Program Files\lscc\diamond\3.10_x64\ispfpga\bin\nt64\scuba.exe -w -n comp -lang verilog -synth synplify -bus_exp 7 -bb -arch xo2c00 -type comp -width 1 -unsigned -port aeqb -pfu  */
/* Thu Nov 14 15:54:50 2019 */


`timescale 1 ns / 1 ps
module comp (DataA, DataB, AEQB)/* synthesis NGD_DRC_MASK=1 */;
    input wire [0:0] DataA;
    input wire [0:0] DataB;
    output wire AEQB;

    wire scuba_vhi;
    wire cmp_inet_0;
    wire cmp_ci;
    wire scuba_vlo;

    defparam LUT4_1.initval =  16'h9009 ;
    ROM16X1A LUT4_1 (.AD3(scuba_vlo), .AD2(scuba_vlo), .AD1(DataA[0]), .AD0(DataB[0]), 
        .DO0(cmp_inet_0));

    VHI scuba_vhi_inst (.Z(scuba_vhi));

    defparam LUT4_0.initval =  16'h8000 ;
    ROM16X1A LUT4_0 (.AD3(cmp_inet_0), .AD2(scuba_vhi), .AD1(scuba_vhi), 
        .AD0(scuba_vhi), .DO0(AEQB));

    VLO scuba_vlo_inst (.Z(scuba_vlo));

    FADD2B cmp_ci_a (.A0(scuba_vlo), .A1(scuba_vlo), .B0(scuba_vlo), .B1(scuba_vlo), 
        .CI(scuba_vlo), .COUT(cmp_ci), .S0(), .S1());



    // exemplar begin
    // exemplar end

endmodule
